# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9481edac435916d6b2f01763ed9d80ff39f912125a920ef5b7c9883ad2995e664a7640f29ed3b20ebf8817992a61ee05cf7bba73502fefe96cd381621a0cf69f

test:
  secret_key_base: d196bea9e8d61353e9be2050f30d0c54b9018fdf007c19463a736aefeb445fca367256d0c7bb7429537f91bdb636147d57f08f9f0799dec4e008d8f8bf6a8471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
